version: 3
  api:
    container_name: apiServer
    restart: always
    build: .
    ports:
      - "80:4000"
  
  database:
    container_name: mysqlServer
    image: mysql
    ports: 
      - "3306:3306"